name: Ansible Lint & Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Run Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

      - name: Setup Python
        uses: actions/setup-python@v7

      - name: Test Build Collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core
          ansible-galaxy collection build .
